An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
JIT session error: Cannot allocate memory
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/nfs/nrdata02-users-data/luciano/script/permABC/figures/sir/sir.py", line 135, in <module>
    smc_reg= perm_abc_smc(key = key, model = mod_reg, y_obs = y_obs_reg, n_particles= N, kernel = KernelTruncatedRW, verbose = 1, epsilon_target = 0., update_weights_distance= False, Final_iteration= Final_iteration, num_blocks_gibbs= n_blocks_reg, both_loc_glob= True, N_iteration_max = N_iterations, alpha_epsilon= alpha)
  File "/mnt/nfs/nrdata02-users-data/luciano/script/permABC/smc.py", line 179, in perm_abc_smc
    thetas[alive], zs[alive], distance_values[alive], ys_index[alive], zs_index[alive], n_lsa, acc_rate, n_sim = move_smc_gibbs_blocks(key = key_move, model = model, thetas = thetas[alive], zs = zs[alive], weights = weights[alive], ys_index = ys_index[alive], zs_index = zs_index[alive], epsilon = epsilon, y_obs = y_obs, distance_values = distance_values[alive], kernel = kernel, H = num_blocks_gibbs, verbose = verbose, both_loc_glob= both_loc_glob, perm = True)
  File "/mnt/nfs/nrdata02-users-data/luciano/script/permABC/moves.py", line 171, in move_smc_gibbs_blocks
    proposed_distances_glob, proposed_ys_index_glob, proposed_zs_index_glob, n_lsa_glob = optimal_index_distance(
  File "/mnt/nfs/nrdata02-users-data/luciano/script/permABC/distances.py", line 78, in optimal_index_distance
    optimal_distances = compute_total_distance(new_zs_index, new_ys_index, local_dist_matrices, global_distances)
  File "/mnt/nfs/nrdata02-users-data/luciano/script/permABC/distances.py", line 34, in compute_total_distance
    return np.sqrt(vmap(jit(lambda matrix, zs_idx, ys_idx, glob: matrix[ys_idx, zs_idx].sum() + glob), in_axes=(0, 0, 0, 0))(local_dist_matrices, zs_index, ys_index,global_distances))
jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: Symbol main.30 not found.
Traceback (most recent call last):
  File "/mnt/nfs/nrdata02-users-data/luciano/script/permABC/figures/sir/sir_figures.py", line 26, in <module>
    with lzma.open('figures/sir/SIR_results{}.xz'.format(seed), 'rb') as f:
  File "/home/users/luciano/miniconda3/envs/permabc_env/lib/python3.10/lzma.py", line 309, in open
    binary_file = LZMAFile(filename, lz_mode, format=format, check=check,
  File "/home/users/luciano/miniconda3/envs/permabc_env/lib/python3.10/lzma.py", line 120, in __init__
    self._fp = builtins.open(filename, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'figures/sir/SIR_results2.xz'
